// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0.0",
    "title" : "FaleMais Telzir API",
    "description" : "Api para clientes Telzir calcular e comparar os custos dos planos Falemais"
  },
  "schemes" : [ "http" ],
  "host" : "localhost:8080",
  "basePath" : "/api/v1",
  "paths" : {
    "/dddcost" : {
      "get" : {
        "description" : "Retorna a lista com todos os DDDs de origem e destino disponíveis",
        "responses" : {
          "200" : {
            "description" : "Sucesso! Retornou a lista com todos os DDDs de origem e destino disponíveis",
            "schema" : {
              "type" : "array",
              "items" : {
                "type" : "object",
                "properties" : {
                  "origin" : {
                    "type" : "integer",
                    "example" : 11
                  },
                  "destination" : {
                    "type" : "integer",
                    "example" : 16
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "schema" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                }
              }
            }
          },
          "404" : {
            "description" : "Not Found",
            "schema" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "schema" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      },
      "post" : {
        "description" : "Retorna os custos dos planos de acordo com os DDDs de origem e destino e do tempo de ligação em minutos",
        "parameters" : [ {
          "name" : "param",
          "in" : "body",
          "schema" : {
            "type" : "object",
            "required" : [ "origin", "destination", "minutes" ],
            "properties" : {
              "origin" : {
                "type" : "integer",
                "example" : 11
              },
              "destination" : {
                "type" : "integer",
                "example" : 18
              },
              "minutes" : {
                "type" : "integer",
                "example" : 200
              }
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully retornou os calulos e comparações",
            "schema" : {
              "type" : "array",
              "items" : {
                "type" : "object",
                "properties" : {
                  "origin" : {
                    "type" : "integer",
                    "example" : 11
                  },
                  "destination" : {
                    "type" : "integer",
                    "example" : 18
                  },
                  "minutes" : {
                    "type" : "integer",
                    "example" : 200
                  },
                  "plan" : {
                    "type" : "array",
                    "items" : {
                      "type" : "object",
                      "properties" : {
                        "name" : {
                          "type" : "string",
                          "example" : "FaleMais 30"
                        },
                        "with" : {
                          "type" : "number",
                          "example" : 168.3
                        },
                        "without" : {
                          "type" : "number",
                          "example" : 180.0
                        }
                      },
                      "example" : [ {
                        "name" : "FaleMais 30",
                        "with" : 168.3,
                        "wihou" : 180.0
                      }, {
                        "name" : "FaleMais 60",
                        "with" : 138.6,
                        "wihou" : 180.0
                      }, {
                        "name" : "FaleMais 120",
                        "with" : 79.2,
                        "wihou" : 180.0
                      } ]
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid request",
            "schema" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                }
              }
            }
          },
          "404" : {
            "description" : "Not Found",
            "schema" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error",
            "schema" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/dddcost",
	Schemes:          []string{},
	Title:            "FaleMais Telzir API",
	Description:      "This is a sample server for Telzir.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
