swagger: '2.0'
info:
  version: 1.0.0
  title: FaleMais Telzir API
  description: Api para clientes telzir calcular e comparar os custos dos planos Falemais
schemes:
  - http
host: "localhost:8080"
basePath: /api/v1
paths:
  /dddcost:
    get:
      description: Retorna a lista com todos os DDDs de origim e destino disponíveis



      responses:
        200:
          description: Sucesso! Retornou a lista com todos os DDDs de origim e destino disponíveis
          schema:
            type: array
            items:
              type: object

              properties:
                origin:
                  type: integer
                  example: 11
                destination:
                  type: integer
                  example: 16


        400:
          description: Invalid request
          schema:
            type: object
            properties:
              message:
                type: string
        404:
          description: Not Found
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      description: Retorna os custos dos planos de acordo com os DDDs de origem e destino e do tempo de ligação em minutos
      parameters:
        - name: param
          in: body
          schema:
            type: object
            required:
              - origin
              - destination
              - minutes
            properties:
              origin:
                type: integer
                example: 11
              destination:
                type: integer
                example: 18
              minutes:
                type: integer
                example: 200


      responses:
        200:
          description: Successfully retornou os calulos e comparações
          schema:
            type: array
            items:
              type: object

              properties:
                origin:
                  type: integer
                  example: 11
                destination:
                  type: integer
                  example: 18
                minutes:
                  type: integer
                  example: 200
                plan:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "FaleMais 30"
                      with:
                        type: number
                        example: 168.30
                      without:
                        type: number
                        example: 180.00
                    example:
                      -
                        name: "FaleMais 30"
                        with: 168.30
                        wihou: 180.00
                      -
                        name: "FaleMais 60"
                        with: 138.6
                        wihou: 180.00
                      -
                        name: "FaleMais 120"
                        with: 79.2
                        wihou: 180.00


        400:
          description: Invalid request
          schema:
            type: object
            properties:
              message:
                type: string
        404:
          description: Not Found
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              message:
                type: string
